### ISSUE TITLE
Problems analyzing "20140210_085"

### ISSUE THREAD

**Issue by dneise** [fact-project/fact-tools#154]
Maybe the input file is corrupt ... might not be a facttools issue... 

call:

```
java -jar -Xmx2500M -Xms2500M     
    /home/guest/neise/facttools_massive_production/single_photon_extractor/fact-tools-v0.16.1.jar
    /home/guest/neise/facttools_massive_production/single_photon_extractor/analysis.xml    
    -DauxFolder=file:/fact/aux/2014/02/10/     
    -Doutfile=file:/scratch/fact/single_photon_extractor_test/json/2014/02/10/20140210_085.json.gz     
    -Dinfile=file:/fact/raw/2014/02/10/20140210_085.fits.fz     
    -Ddrsfile=file:/fact/raw/2014/02/10/20140210_072.drs.fits.gz
```

stdout:

```
Oct 18 2016 00:17:36 [ERROR] stream.io.SourceURL: Failed to register handler for protocol 'hdfs'
Oct 18 2016 00:17:36 [INFO ] stream.util.XIncluder:    url expanded to: 'classpath:/default/data/prevEventAndSkip.xml'
Oct 18 2016 00:17:36 [INFO ] stream.util.XIncluder:    url expanded to: 'classpath:/default/data/calibration.xml'
Oct 18 2016 00:17:36 [INFO ] stream.util.XIncluder:    url expanded to: 'classpath:/default/data/extraction.xml'
Oct 18 2016 00:17:36 [INFO ] stream.util.XIncluder:    url expanded to: 'classpath:/default/data/cleaning.xml'
Oct 18 2016 00:17:36 [INFO ] stream.util.XIncluder:    url expanded to: 'classpath:/default/data/parameterCalc.xml'
Oct 18 2016 00:17:36 [INFO ] stream.util.XIncluder:    url expanded to: 'classpath:/default/data/sourceParameter.xml'
Oct 18 2016 00:17:36 [INFO ] stream.runtime.ProcessContainer: ######## Sources ########
Oct 18 2016 00:17:36 [INFO ] stream.runtime.ProcessContainer: ########fact.io.zfits.ZFitsStream@5d1ae567########
Oct 18 2016 00:17:36 [INFO ] stream.runtime.ProcessContainer:   ==> DefaultProcess['1']
Oct 18 2016 00:17:36 [INFO ] stream.runtime.ProcessContainer: ######## RootSources ########
Oct 18 2016 00:17:36 [INFO ] stream.runtime.ProcessContainer: fact.io.zfits.ZFitsStream@5d1ae567
Oct 18 2016 00:17:36 [INFO ] stream.runtime.ProcessContainer: ######## NonRefSinks ########
Oct 18 2016 00:17:36 [INFO ] stream.runtime.ProcessContainer: ProcessContainer is initialized and ready to start:stream.runtime.ProcessContainer@13f1d038
Oct 18 2016 00:17:36 [INFO ] stream.run: Starting process-container...
Oct 18 2016 00:17:36 [INFO ] fact.io.zfits.ZFitsStream: Reading file: /fact/raw/2014/02/10/20140210_085.fits.fz
Oct 18 2016 00:17:36 [INFO ] fact.io.zfits.ZFitsStream: File is ZFITS compresssed.
Oct 18 2016 00:17:36 [INFO ] fact.io.zfits.ZFitsStream: File contains ZDrsCellOffsets.
```

stderr:

```
stream.util.parser.ParseException: Unknown value while parsing tableheads: '2.60602664639009E-05'
        at fact.io.zfits.FitsHeader.<init>(FitsHeader.java:114)
        at fact.io.zfits.ZFitsUtil.skipToTable(ZFitsUtil.java:122)
        at fact.io.zfits.ZFitsStream.init(ZFitsStream.java:124)
        at stream.runtime.ProcessContainer.execute(ProcessContainer.java:633)
        at stream.runtime.ProcessContainer.run(ProcessContainer.java:594)
        at stream.run.main(run.java:174)
        at stream.run.main(run.java:147)
Exception in thread "main" java.lang.RuntimeException: stream.util.parser.ParseException: Unknown value while parsing tableheads: '2.60602664639009E-05'
        at stream.runtime.ProcessContainer.run(ProcessContainer.java:597)
        at stream.run.main(run.java:174)
        at stream.run.main(run.java:147)
Caused by: stream.util.parser.ParseException: Unknown value while parsing tableheads: '2.60602664639009E-05'
        at fact.io.zfits.FitsHeader.<init>(FitsHeader.java:114)
        at fact.io.zfits.ZFitsUtil.skipToTable(ZFitsUtil.java:122)
        at fact.io.zfits.ZFitsStream.init(ZFitsStream.java:124)
        at stream.runtime.ProcessContainer.execute(ProcessContainer.java:633)
        at stream.runtime.ProcessContainer.run(ProcessContainer.java:594)
        ... 2 more
```

**Comment by mackaiver** [comment]
PR #149 fixes this. The ZFITS reader could not read numbers in scientific notation.
