### ISSUE TITLE
some BufferUnderflowException on some files

### ISSUE THREAD

**Issue by dneise** [fact-project/fact-tools#155]
Doing the std-analysis on some months of data I get BufferUnderflowExceptions on these files:

``` ['20140101_086',
                                                   '20140105_262',
                                                   '20140105_263',
                                                   '20140105_267',
                                                   '20140106_254',
                                                   '20140121_214',
                                                   '20140121_215',
                                                   '20140207_087',
                                                   '20140211_197',
                                                   '20140317_043',
                                                   '20140318_045',
                                                   '20140319_030',
                                                   '20140319_031',
                                                   '20140319_033',
                                                   '20140319_036',
                                                   '20140319_051',
                                                   '20140319_052',
                                                   '20140320_049',
                                                   '20140320_128',
                                                   '20140320_129',
                                                   '20140320_130',
                                                   '20140321_057',
                                                   '20140321_077',
                                                   '20140321_079',
                                                   '20140321_080',
                                                   '20140321_178',
                                                   '20140321_179',
                                                   '20140321_180',
                                                   '20140322_028',
                                                   '20140322_076',
                                                   '20140322_078',
                                                   '20140322_081',
                                                   '20140322_087',
                                                   '20140323_028',
                                                   '20140323_031',
                                                   '20140323_033',
                                                   '20140323_074',
                                                   '20140323_078',
                                                   '20140323_164',
                                                   '20140323_167',
                                                   '20140323_172',
                                                   '20140324_165',
                                                   '20140324_168',
                                                   '20140324_169',
                                                   '20140324_172',
                                                   '20140326_062',
                                                   '20140326_170',
                                                   '20140326_172',
                                                   '20140327_042',
                                                   '20140327_053',
                                                   '20140327_054',
                                                   '20140327_056',
                                                   '20140327_066',
                                                   '20140327_068',
                                                   '20140404_032',
                                                   '20140406_149',
                                                   '20140406_150',
                                                   '20140406_151',
                                                   '20140406_152',
                                                   '20140407_145',
                                                   '20140407_148',
                                                   '20140407_152',
                                                   '20140408_145',
                                                   '20140408_146',
                                                   '20140408_149',
                                                   '20140409_102',
                                                   '20140409_104',
                                                   '20140409_110',
                                                   '20140417_057',
                                                   '20140417_082',
                                                   '20140417_088'],
```

For example like this:

stderr:

```
java.nio.BufferUnderflowException
        at java.nio.HeapByteBuffer.get(HeapByteBuffer.java:145)
        at java.nio.ByteBuffer.get(ByteBuffer.java:694)
        at fact.io.zfits.BlockHeader.unHuffman(BlockHeader.java:120)
        at fact.io.zfits.BlockHeader.decode(BlockHeader.java:162)
        at fact.io.zfits.ZFitsTableReader.readNextRow(ZFitsTableReader.java:74)
        at fact.io.zfits.ZFitsStream.readNext(ZFitsStream.java:193)
        at stream.io.AbstractStream.read(AbstractStream.java:135)
        at stream.runtime.AbstractProcess.execute(AbstractProcess.java:193)
        at stream.runtime.ProcessThread.run(ProcessThread.java:123)
```

stdout:

```
Oct 18 2016 05:16:45 [ERROR] stream.io.SourceURL: Failed to register handler for protocol 'hdfs'
Oct 18 2016 05:16:45 [INFO ] stream.util.XIncluder:    url expanded to: 'classpath:/default/data/prevEventAndSkip.xml'
Oct 18 2016 05:16:46 [INFO ] stream.util.XIncluder:    url expanded to: 'classpath:/default/data/calibration.xml'
Oct 18 2016 05:16:46 [INFO ] stream.util.XIncluder:    url expanded to: 'classpath:/default/data/extraction.xml'
Oct 18 2016 05:16:46 [INFO ] stream.util.XIncluder:    url expanded to: 'classpath:/default/data/cleaning.xml'
Oct 18 2016 05:16:46 [INFO ] stream.util.XIncluder:    url expanded to: 'classpath:/default/data/parameterCalc.xml'
Oct 18 2016 05:16:46 [INFO ] stream.util.XIncluder:    url expanded to: 'classpath:/default/data/sourceParameter.xml'
Oct 18 2016 05:16:46 [INFO ] stream.runtime.ProcessContainer: ######## Sources ########
Oct 18 2016 05:16:46 [INFO ] stream.runtime.ProcessContainer: ########fact.io.zfits.ZFitsStream@4bb12d63########
Oct 18 2016 05:16:46 [INFO ] stream.runtime.ProcessContainer:   ==> DefaultProcess['1']
Oct 18 2016 05:16:46 [INFO ] stream.runtime.ProcessContainer: ######## RootSources ########
Oct 18 2016 05:16:46 [INFO ] stream.runtime.ProcessContainer: fact.io.zfits.ZFitsStream@4bb12d63
Oct 18 2016 05:16:46 [INFO ] stream.runtime.ProcessContainer: ######## NonRefSinks ########
Oct 18 2016 05:16:46 [INFO ] stream.runtime.ProcessContainer: ProcessContainer is initialized and ready to start:stream.runtime.ProcessContainer@62565cf8
Oct 18 2016 05:16:46 [INFO ] stream.run: Starting process-container...
Oct 18 2016 05:16:46 [INFO ] fact.io.zfits.ZFitsStream: Reading file: /fact/raw/2014/04/17/20140417_088.fits.fz
Oct 18 2016 05:16:46 [INFO ] fact.io.zfits.ZFitsStream: File is ZFITS compresssed.
Oct 18 2016 05:16:46 [INFO ] fact.io.zfits.ZFitsStream: File contains ZDrsCellOffsets.
Oct 18 2016 05:16:47 [INFO ] stream.runtime.ProcessContainer: Initializing life-cycle objects...
Oct 18 2016 05:16:47 [INFO ] stream.runtime.ProcessContainer: Creating 1 active processes...
Oct 18 2016 05:16:48 [WARN ] fact.auxservice.AuxFileService$1: The file /fact/aux/2014/04/17/20140417.fits is not a recognized aux service. Could not parse file name into a recognized service.
Oct 18 2016 05:16:48 [INFO ] fact.io.FitsStream: End of file reached. /fact/aux/2014/04/17/20140417.DRIVE_CONTROL_SOURCE_POSITION.fits
Oct 18 2016 05:16:49 [INFO ] fact.io.FitsStream: End of file reached. /fact/aux/2014/04/17/20140417.DRIVE_CONTROL_TRACKING_POSITION.fits
Oct 18 2016 05:16:49 [ERROR] stream.runtime.AbstractProcess: Aborting process due to errors: null
Oct 18 2016 05:16:49 [INFO ] stream.runtime.ProcessContainer$2: Process DefaultProcess['1'] finished!
Oct 18 2016 05:16:49 [INFO ] stream.run: Container finished.
```

I find this `[ERROR] stream.runtime.AbstractProcess: Aborting process due to errors: null` remarkable,
maybe it gives developers a hint....

**Comment by mackaiver** [comment]
I think PR #149 fixes this.
At least for the 10 randomly selected files I took from the list above.
