### ISSUE TITLE
fact.io.hdureader, IllegalArgumentException

### ISSUE THREAD

**Issue by relleums** [fact-project/fact-tools#213]
```
java.lang.IllegalArgumentException: The value for THEAP should be equal to (NAXIS1*NAXIS2 + padding to   2880 blocks).
See section 7.3.2 of the FITS 3.0 standard
        at fact.io.hdureader.BinTable.binTableSanityCheck(BinTable.java:256)
        at fact.io.hdureader.BinTable.<init>(BinTable.java:129)
        at fact.io.hdureader.HDU.<init>(HDU.java:92)
        at fact.io.hdureader.FITS.<init>(FITS.java:88)
        at fact.io.hdureader.FITSStream.init(FITSStream.java:41)
        at stream.runtime.ProcessContainer.execute(ProcessContainer.java:619)
        at stream.runtime.ProcessContainer.run(ProcessContainer.java:572)
        at stream.run.main(run.java:171)
        at stream.run.main(run.java:144)
Exception in thread "main" java.lang.RuntimeException: java.lang.IllegalArgumentException: The value for THEAP should be equal to (NAXIS1*NAXIS2 + padding to 2880 blocks).
See section 7.3.2 of the FITS 3.0 standard
        at stream.runtime.ProcessContainer.run(ProcessContainer.java:575)
        at stream.run.main(run.java:171)
        at stream.run.main(run.java:144)
Caused by: java.lang.IllegalArgumentException: The value for THEAP should be equal to (NAXIS1*NAXIS2 +   padding to 2880 blocks).
See section 7.3.2 of the FITS 3.0 standard
        at fact.io.hdureader.BinTable.binTableSanityCheck(BinTable.java:256)
        at fact.io.hdureader.BinTable.<init>(BinTable.java:129)
        at fact.io.hdureader.HDU.<init>(HDU.java:92)
        at fact.io.hdureader.FITS.<init>(FITS.java:88)
        at fact.io.hdureader.FITSStream.init(FITSStream.java:41)
        at stream.runtime.ProcessContainer.execute(ProcessContainer.java:619)
        at stream.runtime.ProcessContainer.run(ProcessContainer.java:572)
        ... 2 more
```
The following runs aborted processing and wrote sth. to stderr. I checked about 10 of them and it was always the error message from above.

20150407_053
20150407_065
20150407_089
20150407_098
20150407_121
20150407_129
20150407_143
20150407_146
20150408_021
20150408_027
20150408_066
20150408_069
20150408_082
20150408_119
20150408_143
20150408_161
20150408_195
20150408_220
20150408_221
20150408_227
20150409_068
20150409_101
20150409_120
20150409_162
20150409_191
20150409_192
20150410_026
20150410_034
20150410_064
20150410_065
20150410_099
20150410_157
20150410_197
20150411_028
20150411_080
20150411_093
20150411_107
20150411_119
20150411_137
20150411_138
20150411_182
20150411_207
20150412_022
20150412_057

The output can be found at ISDC: ``` /gpfs1/scratch/relleums/single_pulse_pass4/```.
In ```std``` is the stdout and stderr of the workernode job script. In ```job```are the worker node job scripts and in ```phs``` is the photon stream.

All errors when processing 1% (random) of all FACT runs.
I made a machine readable JSON collection of all the errors, the exact input files, and exact program calls:
[error_collection.json.txt](https://github.com/fact-project/fact-tools/files/738867/error_collection.json.txt)

**Comment by relleums** [comment]
I am not an expert on FITS, but might it be, that there is no error but simply the sanity check in
```fact-tools/src/main/java/fact/io/hdureader/BinTable.java``` line 255 should check for unequal instead of equal?
```
int desiredTheap = naxis1*naxis2 + (naxis1 * naxis2) % 2880;
if(theap == desiredTheap){
    throw new IllegalArgumentException("The value for THEAP should be equal to (NAXIS1*NAXIS2 + padding to 2880 blocks)." +"\nSee section 7.3.2 of the FITS 3.0 standard");
}
```
To me it sounds like the error message is contradicting the check in the if clause.
