### ISSUE TITLE
fact.io.hdureader, IllegalStateException

### ISSUE THREAD

**Issue by relleums** [fact-project/fact-tools#214]
```
java.lang.IllegalStateException: Duplicate key Key: (^@^@^@(^@^@^@(^@^@^@(^@^@^@(^@^@^@(^@^@^@(^@^@^@(^@^@^@(^@^@^@(^@^@^@(^@^@^@(^@^@^@(^@^@^@(^@^@^@(^@^@^@(^@^@^@(^@^@^@(^@^@^@(^@^@^@(^@^@^@, Value: ,         Comment: 
        at java.util.stream.Collectors.lambda$throwingMerger$0(Collectors.java:133)
        at java.util.HashMap.merge(HashMap.java:1245)
        at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320)
        at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at fact.io.hdureader.Header.<init>(Header.java:33)
        at fact.io.hdureader.HDU.<init>(HDU.java:86)
        at fact.io.hdureader.FITS.<init>(FITS.java:88)
        at fact.io.hdureader.FITSStream.init(FITSStream.java:41)
        at stream.runtime.ProcessContainer.execute(ProcessContainer.java:619)
        at stream.runtime.ProcessContainer.run(ProcessContainer.java:572)
        at stream.run.main(run.java:171)
        at stream.run.main(run.java:144)
Exception in thread "main" java.lang.RuntimeException: java.lang.IllegalStateException: Duplicate key Key:                                                                                                         (^@^@^@(^@^@^@(^@^@^@(^@^@^@(^@^@^@(^@^@^@(^@^@^@(^@^@^@(^@^@^@(^@^@^@(^@^@^@(^@^@^@(^@^@^@(^@^@^@(^@^@^@(^@^@^@(^@^@^@(^@^@^@(^@^@^@(^@^@^@, Value: , Comment: 
        at stream.runtime.ProcessContainer.run(ProcessContainer.java:575)
        at stream.run.main(run.java:171)
        at stream.run.main(run.java:144)
Caused by: java.lang.IllegalStateException: Duplicate key Key: (^@^@^@(^@^@^@(^@^@^@(^@^@^@(^@^@^@(^@^@^@(^@^@^@(^@^@^@(^@^@^@(^@^@^@(^@^@^@(^@^@^@(^@^@^@(^@^@^@(^@^@^@(^@^@^@(^@^@^@(^@^@^@(^@^@^@(^@^@^@,       Value: , Comment: 
        at java.util.stream.Collectors.lambda$throwingMerger$0(Collectors.java:133)
        at java.util.HashMap.merge(HashMap.java:1245)
        at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320)
        at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at fact.io.hdureader.Header.<init>(Header.java:33)
        at fact.io.hdureader.HDU.<init>(HDU.java:86)
        at fact.io.hdureader.FITS.<init>(FITS.java:88)
        at fact.io.hdureader.FITSStream.init(FITSStream.java:41)
        at stream.runtime.ProcessContainer.execute(ProcessContainer.java:619)
        at stream.runtime.ProcessContainer.run(ProcessContainer.java:572)
        ... 2 more
cp: cannot stat `/tmp/fact_photon_stream_JOB_ID_4460328/*': No such file or directory
```
I read in 1 percent (random) of all the FACT runs covering the whole life time of FACT.  So far 519 runs until 201506xx were processed. 201 jobs did not write to stderr, 318 jobs did write to stderr and did not produce any output. So far I find the error msg from above and the one from #213. All output can be found at isdc: ```/gpfs1/scratch/relleums/pass4_sparse_2011to2017/```

All errors when processing 1% (random) of all FACT runs.
I made a machine readable JSON collection of all the errors, the exact input files, and exact program calls:
[error_collection.json.txt](https://github.com/fact-project/fact-tools/files/738867/error_collection.json.txt)

**Comment by MaxNoe** [comment]
Should also be solved by now, of not, please reopen and provide new info with the current master
