### ISSUE TITLE
fact.io.hdureader, Tile header did not begin with word 'TILE'

### ISSUE THREAD

**Issue by relleums** [fact-project/fact-tools#215]
```
java.io.IOException: Tile header did not begin with word 'TILE'
        at fact.io.hdureader.ZFITSHeapReader$TileHeader.fromStream(ZFITSHeapReader.java:358)
        at fact.io.hdureader.ZFITSHeapReader.getNextRow(ZFITSHeapReader.java:125)
        at fact.io.hdureader.FITSStream.init(FITSStream.java:46)
        at stream.runtime.ProcessContainer.execute(ProcessContainer.java:619)
        at stream.runtime.ProcessContainer.run(ProcessContainer.java:572)
        at stream.run.main(run.java:171)
        at stream.run.main(run.java:144)
Exception in thread "main" java.lang.RuntimeException: java.io.IOException: Tile header did not begin wit
h word 'TILE'
        at stream.runtime.ProcessContainer.run(ProcessContainer.java:575)
        at stream.run.main(run.java:171)
        at stream.run.main(run.java:144)
Caused by: java.io.IOException: Tile header did not begin with word 'TILE'
        at fact.io.hdureader.ZFITSHeapReader$TileHeader.fromStream(ZFITSHeapReader.java:358)
        at fact.io.hdureader.ZFITSHeapReader.getNextRow(ZFITSHeapReader.java:125)
        at fact.io.hdureader.FITSStream.init(FITSStream.java:46)
        at stream.runtime.ProcessContainer.execute(ProcessContainer.java:619)
        at stream.runtime.ProcessContainer.run(ProcessContainer.java:572)
        ... 2 more
cp: cannot stat `/tmp/fact_photon_stream_JOB_ID_4460592/*': No such file or directory
```

In Runs:
20131022_100
20131021_043
20131022_178
20131022_164
20131027_086
20131028_175
20131028_092
20131030_050
20131104_237
20131104_231
20131107_045
20131108_154 and so on...

Find it all in isdc: ```/gpfs1/scratch/relleums/pass4_sparse_2011to2017/```

All errors when processing 1% (random) of all FACT runs.
I made a machine readable JSON collection of all the errors, the exact input files, and exact program calls:
[error_collection.json.txt](https://github.com/fact-project/fact-tools/files/738867/error_collection.json.txt)

**Comment by mackaiver** [comment]
Fixed in #234.
