### ISSUE TITLE
Auxservice, NullPointerException

### ISSUE THREAD

**Issue by relleums** [fact-project/fact-tools#216]
In runs 
20140405_130
20140627_016
```
Exception in thread "Thread-1" java.lang.RuntimeException: Process stopped after exception: java.lang.NullPointerException
        at stream.runtime.ProcessThread.run(ProcessThread.java:170)
Caused by: java.lang.NullPointerException
        at fact.auxservice.AuxFileService.readDataFromFile(AuxFileService.java:92)
        at fact.auxservice.AuxFileService.getAuxiliaryData(AuxFileService.java:66)
        at fact.features.source.SourcePosition.process(SourcePosition.java:212)
        at stream.runtime.AbstractProcess.process(AbstractProcess.java:126)
        at stream.runtime.AbstractProcess.execute(AbstractProcess.java:184)
        at stream.runtime.ProcessThread.run(ProcessThread.java:129)
```

**Comment by mackaiver** [comment]
For some reason I cannot login to the ISDC. Could you try #218 please?

**Comment by relleums** [comment]
All errors when processing 1% (random) of all FACT runs.
I made a machine readable JSON collection of all the errors, the exact input files, and exact program calls:
[error_collection.json.txt](https://github.com/fact-project/fact-tools/files/738867/error_collection.json.txt)
