### ISSUE TITLE
fact.io.zfits.BlockHeader NoSuchElementException

### ISSUE THREAD

**Issue by relleums** [fact-project/fact-tools#239]
fact-tools: master, version 0.18.1, commit c49314cc68693e1e4758b1727714150c24ee9c9c
java: jdk1.8.0_111

Error reading this FACT observation run: ```20141113_209```
The error happened so far only once out of 1000 runs, so its not too crucial.

stdout:
```
Jul 06 2017 08:10:33 [INFO ] stream.util.PropertiesHandler: Reading properties from URL classpath:/default/settings.properties
Jul 06 2017 08:10:34 [INFO ] stream.util.PropertiesHandler: Reading properties from URL classpath:/default/settings.properties
Jul 06 2017 08:10:34 [INFO ] stream.runtime.ProcessContainer: Compute graph:

  {
   'sources': [
  	{ 'id': 'fact', 'class': 'fact.io.zfits.ZFitsStream' }
     ],
   'processes': [
  	{ 'id': '2', 'input': 'fact', 'class': 'stream.runtime.DefaultProcess' }
    ]
  }

Jul 06 2017 08:10:34 [INFO ] stream.run: Starting process-container...
Jul 06 2017 08:10:34 [INFO ] fact.io.zfits.ZFitsStream: Reading file: /data/fact_data/2014/11/13/20141113_209.fits.fz
Jul 06 2017 08:10:34 [INFO ] fact.io.zfits.ZFitsStream: File is ZFITS compresssed.
Jul 06 2017 08:10:34 [INFO ] fact.io.zfits.ZFitsStream: File contains ZDrsCellOffsets.
Jul 06 2017 08:10:37 [INFO ] fact.io.zfits.TileHeader: Id of the TileHeader is wrong, got: '��z'
Jul 06 2017 08:10:37 [ERROR] stream.runtime.AbstractProcess: Error occurred in process '2': The given ordering: '' byte: '16' is not supported
Jul 06 2017 08:10:37 [ERROR] stream.runtime.ProcessThread: java.util.NoSuchElementException: The given ordering: '' byte: '16' is not supported
	at fact.io.zfits.BlockHeader$Ordering.getOrderingFormCharacter(BlockHeader.java:49)
	at fact.io.zfits.BlockHeader.<init>(BlockHeader.java:77)
	at fact.io.zfits.BlockHeader.<init>(BlockHeader.java:62)
	at fact.io.zfits.ZFitsTableReader.readNextRow(ZFitsTableReader.java:73)
	at fact.io.zfits.ZFitsStream.readNext(ZFitsStream.java:197)
	at stream.io.AbstractStream.read(AbstractStream.java:142)
	at stream.runtime.AbstractProcess.execute(AbstractProcess.java:194)
	at stream.runtime.ProcessThread.run(ProcessThread.java:129)

Jul 06 2017 08:10:37 [INFO ] stream.run: Container finished.
Jul 06 2017 08:10:37 [ERROR] stream.runtime.ProcessContainer$3: Process DefaultProcess['2']@7c30a502 signaled an error: The given ordering: '' byte: '16' is not supported
```

stderror:
```
Exception in thread "Thread-2" java.lang.RuntimeException: Process stopped after exception: The given ordering: '' byte: '16' is not supported
	at stream.runtime.ProcessThread.run(ProcessThread.java:170)
```

**Comment by relleums** [comment]
Here are some more affected runs:

NIGHT_RUN
```
grep -rnw 'NoSuchElementException'
20141124_184 [ERROR] java.util.NoSuchElementException: The given ordering: '￿' byte: '-1' is not supported
20141124_185 [ERROR] java.util.NoSuchElementException: The given ordering: '4' byte: '52' is not supported
20141124_186 [ERROR] java.util.NoSuchElementException: The given ordering: '' byte: '3' is not supported
20141124_208 [ERROR] java.util.NoSuchElementException: The given ordering: 'b' byte: '98' is not supported
20141124_210 [ERROR] java.util.NoSuchElementException: The given ordering: '' byte: '1' is not supported
20141211_161 [ERROR] java.util.NoSuchElementException: The given ordering: '￲' byte: '-14' is not supported
20141212_143 [ERROR] java.util.NoSuchElementException: The given ordering: '' byte: '3' is not supported
20141213_180 [ERROR] java.util.NoSuchElementException: The given ordering: '' byte: '1' is not supported
20141213_197 [ERROR] java.util.NoSuchElementException: The given ordering: 'v' byte: '118' is not supported
20141215_161 [ERROR] java.util.NoSuchElementException: The given ordering: 'ﾘ' byte: '-104' is not supported
20141215_190 [ERROR] java.util.NoSuchElementException: The given ordering: '￭' byte: '-19' is not supported
```

**Comment by relleums** [comment]
Its my fault, I used the wrong FITS reader. Can we remove the old one?

**Comment by MaxNoe** [comment]
@relleums Yes, we should!
