### ISSUE TITLE
FACT-Tools has exit code of 0 despite RuntimeException thrown in Writer

### ISSUE THREAD

**Issue by MaxNoe** [fact-project/fact-tools#343]
```
$ java -jar target/fact-tools-v1.0.0.jar examples/save_dl1.xml -Dinfile=file:src/main/resources/testDataFile.fits.gz  -Ddrsfile=file:src/main/resources/testDrsFile.drs.fits.gz -Doutfile=file:test.fits
Mar 10 2018 14:48:53 [INFO ] stream.util.PropertiesHandler: Reading properties from URL classpath:/default/settings.properties
Mar 10 2018 14:48:53 [INFO ] stream.util.PropertiesHandler: Reading properties from URL classpath:/default/settings.properties
Mar 10 2018 14:49:10 [ERROR] stream.runtime.AbstractProcess: Error occurred in process '2': Missing keys for processor fact.io.Writer:  photonCharge

Mar 10 2018 14:49:10 [ERROR] stream.runtime.ProcessThread: java.lang.RuntimeException: Missing keys for processor fact.io.Writer:  photonCharge

	at fact.Utils.mapContainsKeys(Utils.java:306)
	at fact.io.Writer.testKeys(Writer.java:67)
	at fact.io.FITSWriter.process(FITSWriter.java:85)
	at stream.runtime.AbstractProcess.process(AbstractProcess.java:126)
	at stream.runtime.AbstractProcess.execute(AbstractProcess.java:184)
	at stream.runtime.ProcessThread.run(ProcessThread.java:129)

Mar 10 2018 14:49:10 [ERROR] stream.runtime.ProcessContainer$3: Process DefaultProcess['2']@c39f790 signaled an error: Missing keys for processor fact.io.Writer:  photonCharge

Exception in thread "Thread-2" java.lang.RuntimeException: Process stopped after exception: Missing keys for processor fact.io.Writer:  photonCharge

	at stream.runtime.ProcessThread.run(ProcessThread.java:170)
(base) maxnoe@maxnoe-mac {master} ~/Uni/FACT/fact-tools
$ echo $?
0

```

**Comment by MaxNoe** [comment]
Also when Aux data could not be loaded, there is this error:
```
Apr 08 2018 23:55:20 [INFO ] stream.util.PropertiesHandler: Reading properties from URL classpath:/default/settings.properties
Apr 08 2018 23:55:20 [INFO ] stream.util.PropertiesHandler: Reading properties from URL classpath:/default/settings.properties
Apr 08 2018 23:55:21 [WARN ] stream.runtime.setup.ServiceFieldInjection: No service injected for optional service field 'auxService'
Apr 08 2018 23:55:32 [WARN ] fact.features.source.SourcePosition: Using zd and az values from the data item
Apr 08 2018 23:55:41 [WARN ] fact.gainservice.GainService: Time difference to closest gain measurement is more than 5 days
Apr 08 2018 23:55:41 [WARN ] fact.gainservice.GainService: Time difference to closest gain measurement is more than 5 days
Apr 08 2018 23:55:41 [ERROR] fact.auxservice.AuxFileService: Could not load aux file in given directory file:/fact/aux/2011/11/16
Apr 08 2018 23:55:41 [ERROR] fact.Utils: Data does not contain the key shower
Apr 08 2018 23:55:41 [ERROR] stream.runtime.AbstractProcess: Error occurred in process '2': Did not find key 'shower' in the event. For processor:  fact.pixelsets.Length
Apr 08 2018 23:55:41 [ERROR] stream.runtime.ProcessThread: java.lang.RuntimeException: Did not find key 'shower' in the event. For processor:  fact.pixelsets.Length
        at fact.Utils.isKeyValid(Utils.java:329)
        at fact.pixelsets.Length.process(Length.java:28)
        at stream.runtime.AbstractProcess.process(AbstractProcess.java:126)
        at stream.runtime.AbstractProcess.execute(AbstractProcess.java:184)
        at stream.runtime.ProcessThread.run(ProcessThread.java:129)

Apr 08 2018 23:55:41 [ERROR] stream.runtime.ProcessContainer$3: Process DefaultProcess['2']@6bf256fa signaled an error: Did not find key 'shower' in the event. For processor:  fact.pixelsets.Length
Copying /tmp/7879806.1.fact_short/fact_erna_job_id_251320_rgz5q6xz/facttools_output/20111116_016_v1.0.0_std_analysis_level2.fits to /gpfs0/fact/processing/erna/fact-tools/v1.0.0/std_analysis/2011/11/16```

And exit code was still 0.
