### ISSUE TITLE
Process stopped after exception: Index: 0, Size: 0

### ISSUE THREAD

**Issue by jebuss** [fact-project/fact-tools#366]
When running the pedestal sampling from the `sample_pedestal_noise` branch with `examples/add_pedestal_noise_template.xml`. I sometimes get the following error. Not sure how to reproduce where and when it happends, but it seems to allways happen once when sampling over one of the proton MC sets. 

```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:657)
        at java.util.ArrayList.get(ArrayList.java:433)
        at fact.io.hdureader.FITS.<init>(FITS.java:105)
        at fact.io.hdureader.FITSStream.init(FITSStream.java:48)
        at fact.io.FactFileListMultiStream.readNext(FactFileListMultiStream.java:148)
        at stream.io.AbstractStream.read(AbstractStream.java:142)
        at stream.runtime.AbstractProcess.execute(AbstractProcess.java:195)
        at stream.runtime.ProcessThread.run(ProcessThread.java:129)
Exception in thread "Thread-1" java.lang.RuntimeException: Process stopped after exception: Index: 0, Size: 0
        at stream.runtime.ProcessThread.run(ProcessThread.java:171)
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:657)
        at java.util.ArrayList.get(ArrayList.java:433)
        at fact.io.hdureader.FITS.<init>(FITS.java:105)
        at fact.io.hdureader.FITSStream.init(FITSStream.java:48)
        at fact.io.FactFileListMultiStream.readNext(FactFileListMultiStream.java:148)
        at stream.io.AbstractStream.read(AbstractStream.java:142)
        at stream.runtime.AbstractProcess.execute(AbstractProcess.java:195)
        at stream.runtime.ProcessThread.run(ProcessThread.java:129)
streams exited on error: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
java.lang.RuntimeException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at stream.runtime.ProcessContainer.run(ProcessContainer.java:580)
        at stream.run.main(run.java:168)
        at stream.run.main(run.java:147)
        at fact.run.main(run.java:26)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:657)
        at java.util.ArrayList.get(ArrayList.java:433)
        at fact.io.hdureader.FITS.<init>(FITS.java:105)
        at fact.io.hdureader.FITSStream.init(FITSStream.java:48)
        at fact.io.FactFileListMultiStream.readNext(FactFileListMultiStream.java:148)
        at stream.io.AbstractStream.read(AbstractStream.java:142)
        at stream.runtime.AbstractProcess.execute(AbstractProcess.java:195)
        at stream.runtime.ProcessThread.run(ProcessThread.java:129)
2018-06-18 14:11:51,733 - erna.stream_runner_local_output - ERROR - Fact tools returned an error:
```

**Comment by Facundotoledo** [comment]
cristian
