### ISSUE TITLE
BlockingQueue and process with copies

### ISSUE THREAD

**Issue by mackaiver** [fact-project/fact-tools#78]
Originally reported by: **Maximilian Nöthe (Bitbucket: [MaxNoe](http://bitbucket.org/MaxNoe), GitHub: [MaxNoe](http://github.com/MaxNoe))**

---

If I run the following xml, I get an errror about an invalid Mark:

``` xml
<application>
    <property name="infile" value=""/>

    <stream id="fact" class="fact.io.FitsStream" url="file:gamma_mc.fits.gz" />
    <stream.io.BlockingQueue id="queue" />

    <process input="fact" copies="2">
        <fact.utils.Remapping key="Data" outputKey="Data"/>
        <fact.datacorrection.DrsCalibration url="classpath:/testMcDrsFile.drs.fits.gz"/>
        <fact.filter.GaussConvolution key="DataCalibrated" outputKey="SmoothedData"/>
        <fact.tutorial.SimpleRisingEdgeExtraction/>
        <fact.tutorial.SimplePhotonchargeExtraction/>
        <fact.tutorial.Cleaning threshold="6"/>
        <fact.tutorial.HillasParameter />
        <Enqueue queue="queue"/>
    </process>

    <process input="queue">
        <fact.io.PrintKeysOnConsole keys="EventNum"/>
    </process>
</application>
```

The error is the following:

```
Jul 30 2015 17:07:54 [ERROR] stream.runtime.AbstractProcess: Aborting process due to errors: Resetting to invalid mark
java.io.IOException: Resetting to invalid mark
    at java.io.BufferedInputStream.reset(BufferedInputStream.java:437)
    at java.io.FilterInputStream.reset(FilterInputStream.java:226)
    at fact.io.FitsStream.readNext(FitsStream.java:376)
    at stream.io.AbstractStream.read(AbstractStream.java:135)
    at stream.runtime.AbstractProcess.execute(AbstractProcess.java:197)
    at stream.runtime.ProcessThread.run(ProcessThread.java:125)
Jul 30 2015 17:07:54 [INFO ] stream.runtime.ProcessContainer$2: Process DefaultProcess['58b6a0c9-b218-4379-875b-fc73c6051e1d'] finished!
Jul 30 2015 17:07:54 [ERROR] stream.runtime.AbstractProcess: Aborting process due to errors: -520
java.lang.ArrayIndexOutOfBoundsException: -520
    at fact.datacorrection.DrsCalibration.applyDrsCalibration(DrsCalibration.java:260)
    at fact.datacorrection.DrsCalibration.process(DrsCalibration.java:159)
    at stream.runtime.AbstractProcess.process(AbstractProcess.java:126)
    at stream.runtime.AbstractProcess.execute(AbstractProcess.java:186)
    at stream.runtime.ProcessThread.run(ProcessThread.java:125
```

Everything works if I use `copies="1"`

---
- Bitbucket: https://bitbucket.org/cbockermann/fact-tools/issue/78

**Comment by MaxNoe** [comment]
Closing as this is an issue in streams
