### ISSUE TITLE
fact-tools cannot  read drs files in classpath

### ISSUE THREAD

**Issue by mackaiver** [fact-project/fact-tools#90]
Originally reported by: **Maximilian Nöthe (Bitbucket: [MaxNoe](http://bitbucket.org/MaxNoe), GitHub: [MaxNoe](http://github.com/MaxNoe))**

---

Using the default in settings_mc.properties (`drsfile=classpath:/stdMcDrsFile.drs.fits.gz`)

I get:

```
$ java -jar target/fact-tools-0.11.0.jar examples/mc_viewer.xml 
Jan 15 2016 19:48:18 [ERROR] stream.io.SourceURL: Failed to register handler for protocol 'hdfs'
Jan 15 2016 19:48:18 [INFO ] stream.util.XIncluder:    url expanded to: 'classpath:/default/mc/calibration_mc.xml'
Jan 15 2016 19:48:18 [INFO ] stream.util.XIncluder:    url expanded to: 'classpath:/default/mc/extraction_mc.xml'
Jan 15 2016 19:48:18 [INFO ] stream.util.XIncluder:    url expanded to: 'classpath:/default/mc/cleaning_mc.xml'
Jan 15 2016 19:48:18 [INFO ] stream.runtime.ProcessContainer: ######## Sources ########
Jan 15 2016 19:48:18 [INFO ] stream.runtime.ProcessContainer: ########fact.io.FitsStream@2938b0d5########
Jan 15 2016 19:48:18 [INFO ] stream.runtime.ProcessContainer:   ==> DefaultProcess['2']
Jan 15 2016 19:48:18 [INFO ] stream.runtime.ProcessContainer: ######## RootSources ########
Jan 15 2016 19:48:18 [INFO ] stream.runtime.ProcessContainer: fact.io.FitsStream@2938b0d5
Jan 15 2016 19:48:18 [INFO ] stream.runtime.ProcessContainer: ######## NonRefSinks ########
Jan 15 2016 19:48:18 [INFO ] stream.runtime.ProcessContainer: ProcessContainer is initialized and ready to start:stream.runtime.ProcessContainer@735dcd1d
Jan 15 2016 19:48:18 [INFO ] stream.run: Starting process-container...
Jan 15 2016 19:48:18 [INFO ] stream.runtime.ProcessContainer: Initializing life-cycle objects...
Jan 15 2016 19:48:18 [INFO ] stream.runtime.ProcessContainer: Creating 1 active processes...
Jan 15 2016 19:48:18 [ERROR] fact.datacorrection.DrsCalibration: Failed to load DRS data: null
Jan 15 2016 19:48:18 [ERROR] fact.datacorrection.DrsCalibration: Could not load .drs file specified in the url.
java.lang.RuntimeException
    at fact.datacorrection.DrsCalibration.init(DrsCalibration.java:293)
    at stream.runtime.AbstractProcess.init(AbstractProcess.java:144)
    at stream.runtime.ProcessThread.init(ProcessThread.java:110)
    at stream.runtime.ProcessContainer.execute(ProcessContainer.java:675)
    at stream.runtime.ProcessContainer.run(ProcessContainer.java:594)
    at stream.run.main(run.java:174)
    at stream.run.main(run.java:147)
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException
    at stream.runtime.ProcessContainer.run(ProcessContainer.java:597)
    at stream.run.main(run.java:174)
    at stream.run.main(run.java:147)
Caused by: java.lang.RuntimeException
    at fact.datacorrection.DrsCalibration.init(DrsCalibration.java:293)
    at stream.runtime.AbstractProcess.init(AbstractProcess.java:144)
    at stream.runtime.ProcessThread.init(ProcessThread.java:110)
    at stream.runtime.ProcessContainer.execute(ProcessContainer.java:675)
    at stream.runtime.ProcessContainer.run(ProcessContainer.java:594)
    ... 2 more
```

---
- Bitbucket: https://bitbucket.org/cbockermann/fact-tools/issue/90

**Comment by MaxNoe** [comment]
This is due to the exclusion of those file in the pom.xml. We should get rid of this

**Comment by MaxNoe** [comment]
This was broken again with the new HDUReader as it is not using the logic of the old FITSStream to read stuff from classpath
